config/routes.rb
Rails.application.routes.draw do
  resources :links, only: [:show, :new, :create] do
    resource :upvote, only: [:create]
    resource :downvote, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      resources :links, only: [:index, :create]
    end
  end

  get "/new", to: "new_links#index", as: "new_links"

  root to: "links#index"
end

app/models/link.rb
class Link < ActiveRecord::Base
  IMAGE_FORMATS = %w(.jpg .gif .png)

  validates :title, presence: true
  validates :url, presence: true

  def self.hottest_first
    order("upvotes - downvotes DESC")
  end

  def self.newest_first
    order(created_at: :desc)
  end

  def upvote
    increment!(:upvotes)
  end

  def downvote
    increment!(:downvotes)
  end

  def score
    Score.new(self)
  end

  def image?
    url.end_with? *IMAGE_FORMATS
  end
end

app/models/score.rb
class Score
  CONTROVERSIAL_THRESHOLD = 0.2

  attr_reader :upvotes, :downvotes

  def initialize(link)
    @upvotes = link.upvotes
    @downvotes = link.downvotes
  end

  def value
    upvotes - downvotes
  end

  def controversial?
    score_delta_percentage < CONTROVERSIAL_THRESHOLD
  end

  def ==(other)
    other.upvotes == upvotes && other.downvotes == downvotes
  end

  alias :eql? :==

  def hash
    [upvotes, downvotes].hash
  end

  private

  def score_delta_percentage
    score_delta.to_f / high_score
  end

  def high_score
    [upvotes, downvotes].max
  end

  def score_delta
    value.abs
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < Api::BaseController
  def index
    links = Link.hottest_first
    render json: links
  end

  def create
    link = Link.new(link_params)

    if link.save
      render json: link, status: :created
    else
      render json: { errors: link.errors.full_messages },
        status: :unprocessable_entity
    end
  end

  private

  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/downvotes_controller.rb
class DownvotesController < ApplicationController
  def create
    link = Link.find(params[:link_id])
    link.downvote

    redirect_to :back
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
     @links = Link.all
  end

  def new
     @link = Link.new
  end

  def create
  @link = Link.create(link_params)

    if @link.save
      redirect_to @link
    else
      render :new
    end
  end

  def show
    @link = Link.find(params[:id])
  end

  private

  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/new_links_controller.rb
class NewLinksController < ApplicationController
  def index
    @links = Link.newest_first

    render "links/index"
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def create
    link = Link.find(params[:link_id])
    link.upvote

    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_score_for(score)
    "#{score.value} (+#{score.upvotes}, -#{score.downvotes})"
  end
end

app/views/application/_error_messages.html.erb
<% if target.errors.any? %>
  <div>
    <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
      <ul>
        <% target.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/application/_navigation.html.erb
<nav>
  <ul>
    <li><%= link_to "hot", :root %></li>
    <li><%= link_to "new", [:new, :links] %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "navigation" %>

  <%= yield %>

</body>
</html>

app/views/links/_link.html.erb
<%= link_to link.url do %>
  <%= link.title %>

  <% if link.image? %>
    <%= image_tag link.url %>
  <% end %>
<% end %>

app/views/links/_link_list_item.html.erb
<%= content_tag_for :li, link do %>
  <%= link_to "Upvote", [link, :upvote], method: :post %>
  <div data-role="score"><%= formatted_score_for(link.score) %></div>
  <%= link_to "Downvote", [link, :downvote], method: :post %>

  <%= render link %>
<% end %>

app/views/links/index.html.erb
<%= link_to "Submit a new link!", new_link_path %>

<ul id="links">
  <%= render partial: "links/link_list_item", collection: @links, as: :link %>
</ul>

app/views/links/new.html.erb
<%= form_for @link do |form| %>
  <%= render "error_messages", target: @link %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <%= form.submit "Submit!" %>
<% end %>

app/views/links/show.html.erb
<%= render @link %>